In [1]:
import pandas as pd

In [2]:
observed = pd.read_csv('targets_already_scheduled.csv')

In [3]:
# Using the footprint that exclude the targets to block
# SAVING TIME for some pulsar search survey things 
footprint = pd.read_csv('MMGPS-SBAND_pointing_grid_final_blocked.csv')
full_footprint = pd.read_csv('MMGPS-SBAND_pointing_grid_final.csv')

In [4]:
# Find the blocked pointings (targets in a full footprint, not in a blocked footprint)
blocked = full_footprint[~full_footprint['Pointing'].isin(footprint['Pointing'])]

# Find the observed Targets that are in full footprint 
observed = full_footprint[full_footprint['Pointing'].isin(observed['Pointing'])]

# Find outstanding targets (Not observed) 
# outstanding = full_footprint[~full_footprint['Pointing'].isin(observed['Pointing'])]

In [23]:
with pd.ExcelWriter('Obs_tracking.xlsx', engine='xlsxwriter') as writer:
    # Merge Full footprint and observed targets 
    df_merged = pd.merge(full_footprint.drop(columns=['Gb','RA', 'Dec']), observed.drop(columns=['Gb','RA', 'Dec']), on='Pointing', how='left')

    # Drop the unnecessary  Glx column and replace the observed Glx with either False if NaN 
    # or True if not (To show that the observation is observed or not); 
    # Re-label the column keys accordingly 
    df = df_merged.drop(columns=['Gl_x'])
    df['Gl_y'] = ~df['Gl_y'].isna()
    new_df = df.rename(columns={'Gl_y': 'Observed/Scheduled?'})
    new_df.to_excel(writer, sheet_name='Sheet1', index=False)
new_df

          Pointing  Observed/Scheduled?
0     MSGPS_S_0000                 True
1     MSGPS_S_0001                 True
2     MSGPS_S_0002                 True
3     MSGPS_S_0003                 True
4     MSGPS_S_0004                 True
...            ...                  ...
3614  MSGPS_S_3614                False
3615  MSGPS_S_3615                False
3616  MSGPS_S_3616                False
3617  MSGPS_S_3617                False
3618  MSGPS_S_3618                False

[3619 rows x 2 columns]

In [98]:
new_df

          Pointing  Observed/Scheduled?
0     MSGPS_S_0000                 True
1     MSGPS_S_0000                 True
2     MSGPS_S_0000                 True
3     MSGPS_S_0000                 True
4     MSGPS_S_0000                 True
...            ...                  ...
6132  MSGPS_S_3614                False
6133  MSGPS_S_3615                False
6134  MSGPS_S_3616                False
6135  MSGPS_S_3617                False
6136  MSGPS_S_3618                False

[6137 rows x 2 columns]