In [1]:
import pandas as pd

In [2]:
all_pointings = 'MMGPS-SBAND_pointing_grid_final.csv'
blocked_survey_pointings = 'MMGPS-SBAND_pointing_grid_final_blocked.csv'
observed_pointings = 'targets_already_scheduled_20240717.csv' # Observed as of 2024 July 17
observed_pointings_today = 'targets_already_scheduled.csv'    # Observed as of 2024 July 17 + TODAY AND all others

In [3]:
survey_pointing = pd.read_csv(all_pointings)
blocked_survey = pd.read_csv(blocked_survey_pointings)
observed_survey = pd.read_csv(observed_pointings)
observed_survey_today = pd.read_csv(observed_pointings_today)

In [6]:
# Find items in survey_pointings that are not in blocked_servey pointings
blocked_pointings = pd.concat([survey_pointing,blocked_survey]).drop_duplicates(keep=False)

In [24]:
# Find items in survey_pointings that are observed upto july 17 2024
sur = survey_pointing.rename(columns={'Dec':'DEC'})
pd.concat([sur,observed_survey])

,Pointing,Gl,Gb,RA,DEC,Obs_time_UTC,Obs_Time_LST
0,MSGPS_S_0000,-79.711501,-1.355751,9:55:45.19,-56:17:56.74,NaN,NaN
1,MSGPS_S_0001,-79.855751,-1.105904,9:56:2.73,-56:00:48.59,NaN,NaN
2,MSGPS_S_0002,-79.711501,-0.856057,9:57:57.3,-55:54:17.39,NaN,NaN
3,MSGPS_S_0003,-79.855751,-0.606209,9:58:13.69,-55:37:8.06,NaN,NaN
4,MSGPS_S_0004,-79.711501,-0.356362,10:00:6.75,-55:30:29.37,NaN,NaN
...,...,...,...,...,...,...,...
752,MSGPS_S_1641,NaN,NaN,15:31:27.13,-57:16:00.7,2024-06-20 16:12:39,11:35:52.47838176
753,MSGPS_S_1850,NaN,NaN,16:02:00.98,-53:53:04.6,2024-06-20 16:36:31,11:59:48.39924243
754,MSGPS_S_2058,NaN,NaN,16:28:17.57,-50:22:29.0,2024-06-20 17:00:15,12:23:36.2981995
755,MSGPS_S_2354,NaN,NaN,17:00:08.45,-44:31:57.0,2024-06-20 17:26:33,12:49:58.61881422
756,MSGPS_S_2653,NaN,NaN,17:22:30.97,-37:57:13.0,2024-06-20 17:50:20,13:13:49.52598676

In [12]:
survey_pointing

          Pointing         Gl        Gb           RA           Dec
0     MSGPS_S_0000 -79.711501 -1.355751   9:55:45.19  -56:17:56.74
1     MSGPS_S_0001 -79.855751 -1.105904    9:56:2.73  -56:00:48.59
2     MSGPS_S_0002 -79.711501 -0.856057    9:57:57.3  -55:54:17.39
3     MSGPS_S_0003 -79.855751 -0.606209   9:58:13.69   -55:37:8.06
4     MSGPS_S_0004 -79.711501 -0.356362   10:00:6.75  -55:30:29.37
...            ...        ...       ...          ...           ...
3614  MSGPS_S_3614  14.916026  0.143332   18:17:10.3  -15:54:33.34
3615  MSGPS_S_3615  14.771777  0.393179  18:15:58.33   -15:55:2.48
3616  MSGPS_S_3616  14.916026  0.643026  18:15:20.68  -15:40:17.39
3617  MSGPS_S_3617  14.771777  0.892873   18:14:8.79  -15:40:44.25
3618  MSGPS_S_3618  14.916026  1.142720  18:13:31.32  -15:25:58.05

[3619 rows x 5 columns]

In [14]:
observed_survey

,Pointing,RA,DEC,Obs_time_UTC,Obs_Time_LST
0,MSGPS_S_0000,9:55:45.19,-56:17:56.7,2023-03-07 15:21:52,3:47:59.20658543
1,MSGPS_S_0001,9:56:02.73,-56:00:48.6,2023-03-07 15:52:38,4:18:50.26057742
2,MSGPS_S_0002,9:57:57.30,-55:54:17.4,2023-03-07 16:09:42,4:35:57.06409167
3,MSGPS_S_0003,9:58:13.69,-55:37:08.1,2023-03-07 16:33:13,4:59:31.92713688
4,MSGPS_S_0004,10:00:06.75,-55:30:29.4,2023-03-07 16:56:49,5:23:11.80387077
...,...,...,...,...,...
752,MSGPS_S_1641,15:31:27.13,-57:16:00.7,2024-06-20 16:12:39,11:35:52.47838176
753,MSGPS_S_1850,16:02:00.98,-53:53:04.6,2024-06-20 16:36:31,11:59:48.39924243
754,MSGPS_S_2058,16:28:17.57,-50:22:29.0,2024-06-20 17:00:15,12:23:36.2981995
755,MSGPS_S_2354,17:00:08.45,-44:31:57.0,2024-06-20 17:26:33,12:49:58.61881422
756,MSGPS_S_2653,17:22:30.97,-37:57:13.0,2024-06-20 17:50:20,13:13:49.52598676